---
- name: Install Common Elastic and Logstash
  hosts: logstash
  user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - nginx
    - awstools
    - java
    - elasticsearch
    - kibana
    - logstash


- name: Install elasticsearch
  hosts: dev1
  user: root
  # remote_user: user
  # sudo: yes

  roles:
    - java
    - elasticsearch